name: 'Dev Deployment'
on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: './environments/lightsail_instance/'
  AWS_ACCESS_KEY_ID: AKIAVZBHJVXJHYIZPANV
  AWS_SECRET_ACCESS_KEY: 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

  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deployment:
    name: 'Terragrunt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.55.2

      - name: Interact with Terragrunt
        run: terragrunt --version

      - name: 'Setup Git Global Config'
        run: |
          git config --global url."https://${{ secrets.PAT }}@github".insteadOf https://github

      # - name: 'Terragrunt Init'
      #   run: terragrunt run-all init --terragrunt-non-interactive
      #   working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 'Terragrunt Plan'
        run: terragrunt run-all plan --terragrunt-non-interactive
        working-directory: ${{ env.WORKING_DIRECTORY }}
