name: Terragrunt Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 5.33.0

      - name: Setup Terragrunt CLI
        run: |
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.1/terragrunt_linux_amd64_v0.34.1.tar.gz | tar xvz
          sudo mv terragrunt /usr/local/bin

      # - name: Initialize Terragrunt
      #   run: |
      #     cd /path/to/terraform/module
      #     terragrunt init

      - name: Terragrunt Plan
        run: |
          cd environments/lightsail_instance/
          terragrunt plan -out=tfplan

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd environments/lightsail_instance/
          terragrunt apply -auto-approve tfplan


      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd environments/lightsail_instance/
          terragrunt destroy -auto-approve tfplan
